"""remove estoque de produtoa

Revision ID: 3c527a3da6d1
Revises: 18e2639d5408
Create Date: 2026-05-23 22:18:24.962065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c527a3da6d1'
down_revision: Union[str, Sequence[str], None] = '18e2639d5408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'estoque')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
