"""adiciona estoque em produto

Revision ID: 72c6d783fea1
Revises: eedeab81bbc2
Create Date: 2026-05-23 22:11:18.179125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c6d783fea1'
down_revision: Union[str, Sequence[str], None] = 'eedeab81bbc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marcas', sa.Column('estoque', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marcas', 'estoque')
    # ### end Alembic commands ###
