"""adiciona estoque em produto

Revision ID: b1e25b239a99
Revises: 5c12f7331cd1
Create Date: 2026-05-23 22:15:33.179179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e25b239a99'
down_revision: Union[str, Sequence[str], None] = '5c12f7331cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'estoque')
    # ### end Alembic commands ###
